### ISSUE TITLE
Great thanks

### ISSUE THREAD

**Issue by marcusradell** [stefanprodan/aspnetcore-dockerswarm#1]
I just followed the guide on how to setup a rethinkdb cluster. It's the first time I did anything with docker swarm as well as rethinkdb.

I'm so grateful for the guide. It's exactly what I needed to evaluate rethinkdb on swarm. Big thanks!

(oh, just close the issue btw. it's just a praise.)

**Comment by stefanprodan** [comment]
Thank you @marcusnielsen 

I'm experimenting now with unified logging solutions for Docker Swarm. Setting up a cluster seems pretty easy but monitoring services and nods is not so straightforward

**Comment by marcusradell** [comment]
Not surprised that logging and monitoring is a harder issue :-P

Have you encountered the issue with the admin logging `Rejected a connection from server e60149b4-57a4-4fe7-b038-04f418d13177 since one is open already.` ?
https://github.com/rethinkdb/rethinkdb/issues/5456

Since it's docker-based you should have seen the same thing, right?

Hope to see how it goes with the logging solution!

**Comment by stefanprodan** [comment]
The cluster consolidation will take some minutes. So you will get that warning a lot at the beginning. I've done some intense load testing on the cluster with GB of data and that warning didn't cause any data loss.

**Comment by marcusradell** [comment]
Sounds like it worked for you then. Mine kept logging that for 3h, so it would screw logging up. But I believe it will get fixed soon enough. Cheers!
