### ISSUE TITLE
Don't use `dotnet run` as container entrypoint

### ISSUE THREAD

**Issue by glennc** [stefanprodan/aspnetcore-dockerswarm#2]
using `dotnet run` as the entrypoint of a container isn't something you should do in a production container. `dotnet run` is for dev machines.

`dotnet run` compiles the app and then runs the output, in a Docker runtime image you should instead do a `dotnet publish` as part of the image build and then have `dotnet <assemblyName>` as the entrypoint of your container. That way you have faster start times for your container and you are more immutable because the app is fully baked during image build instead of doing compilation at runtime.

Does that make sense?

**Comment by stefanprodan** [comment]
Yes I totally agree with you. 
My approach at running  .NET Core in production is by using `dotnet` `build`, `test` and `publish` inside **_microsoft/dotnet**_ image. Then, with the published output, I use  **_microsoft/aspnetcore**_ with `ENTRYPOINT ["dotnet", "app.dll"]`.  I've described this process [here](https://stefanprodan.com/2016/aspnetcore-cd-pipeline-docker-hub/).

I'm going to update this repo too, thanks for pointing this out to me.

**Comment by glennc** [comment]
I'll be sure to read through your other stuff as well, thanks :). Good job by the way, I haven't had a chance to read most of this stuff in detail but it looks like a great set of information.
